/*
 * Menu data for Loi's — The Joy of Phở
 * Each category has a Vietnamese name, an English subtitle, and a list of items.
 * Best sellers (with photos) are defined separately and reference real dish images.
 */

/* Seed reviews shown to every visitor (sample customer feedback). */
const SAMPLE_REVIEWS = [
  {
    name: "Minh T.",
    rating: 5,
    message:
      "Best phở in Newmarket, hands down. The House Special broth is so rich and the beef melts in your mouth. Tastes just like home.",
    at: "2026-05-28",
  },
  {
    name: "Sarah L.",
    rating: 5,
    message:
      "The fresh spring rolls and the lemongrass chicken vermicelli were incredible. Friendly staff and quick service. Will be back!",
    at: "2026-05-21",
  },
  {
    name: "David Nguyen",
    rating: 4,
    message:
      "Authentic Bún Bò Huế with a real kick. Big portions for the price. Bubble tea was a nice sweet finish.",
    at: "2026-05-12",
  },
  {
    name: "Priya R.",
    rating: 5,
    message:
      "Came for the Cơm Tấm and left so happy — the grilled pork was perfectly charred. Cozy spot inside RioCentre.",
    at: "2026-04-30",
  },
  {
    name: "Jason W.",
    rating: 4,
    message:
      "Great vegetarian options! The Phở Chay broth had so much flavor. Loved the Vietnamese iced coffee too.",
    at: "2026-04-18",
  },
  {
    name: "Amanda K.",
    rating: 5,
    message:
      "Fish sauce chicken wings are addictive and the bánh mì is fresh and crunchy. A new family favourite.",
    at: "2026-04-05",
  },
];

const BEST_SELLERS = [
  {
    name: "The Joy Of Phở — Đặc Biệt",
    code: "P-01",
    en: "House Special Combination Phở",
    desc: "Our signature rice noodle soup with rare beef, brisket, tendon, tripe & meatballs in a 12-hour broth.",
    price: "$15.99",
    img: "House Special Pho.jpg",
    tag: "Signature",
  },
  {
    name: "Bún Bò Huế",
    code: "BU-01",
    en: "Spicy Beef Vermicelli Soup",
    desc: "Bold, lemongrass-and-chili broth with beef, pork and ham — a fiery Central-Vietnam classic.",
    price: "$15.99",
    img: "Spicy Beef noodle.jpg",
    tag: "Spicy",
  },
  {
    name: "Gỏi Cuốn Tôm Thịt",
    code: "A-06",
    en: "Fresh Prawn & Pork Salad Rolls",
    desc: "Cool rice-paper rolls packed with shrimp, pork, herbs & vermicelli, served with peanut sauce.",
    price: "$8.99",
    img: "Fresh Spring Rolls with Peanut Sauce.jpg",
    tag: "Fresh",
  },
  {
    name: "Cơm Tấm Đặc Biệt",
    code: "CT-01",
    en: "House Special Broken Rice",
    desc: "Grilled lemongrass pork chop, Vietnamese sausage and a sunny fried egg over broken rice.",
    price: "$16.99",
    img: "Lemongrass Pork with Rice and Egg.jpg",
    tag: "Popular",
  },
  {
    name: "Bún Gà Nướng Sả & Chả Giò",
    code: "BU-06",
    en: "Grilled Lemongrass Chicken & Spring Rolls",
    desc: "Charred lemongrass chicken and crispy spring rolls over fresh vermicelli with herbs.",
    price: "$16.99",
    img: "Lemongrass Grilled Chicken and Spring rolls.jpg",
    tag: "Popular",
  },
  {
    name: "Bánh Mì Bò Nướng",
    code: "BM-06",
    en: "Grilled Beef Steak Bánh Mì",
    desc: "Toasty baguette layered with grilled beef, pâté, pickled veg, cilantro & chili.",
    price: "$9.50",
    img: "Beef Stew Banh Mi.jpg",
    tag: "Handheld",
  },
  {
    name: "Pad Thái Tôm",
    code: "PT-04",
    en: "Shrimp Pad Thai",
    desc: "Stir-fried rice noodles with shrimp, egg, bean sprouts and crushed peanuts.",
    price: "$17.99",
    img: "Shrimp Pad Thai.jpg",
    tag: "Wok",
  },
  {
    name: "Phở Chay",
    code: "P-13",
    en: "Vegetable & Tofu Phở",
    desc: "Fragrant vegetarian broth with tofu and seasonal vegetables over rice noodles.",
    price: "$15.99",
    img: "Pho Chay.jpg",
    tag: "Vegetarian",
  },
  {
    name: "Cánh Gà Chiên Nước Mắm",
    code: "FM-01",
    en: "Fish Sauce Chicken Wings",
    desc: "Crispy wings tossed in a sweet-savory caramelized fish-sauce glaze.",
    price: "$17.99",
    img: "Chicken Wings.jpg",
    tag: "Shareable",
  },
  {
    name: "Brown Sugar Bubble Tea",
    code: "M-01",
    en: "Joy of Bubble",
    desc: "Sweet, rich brown sugar milk tea with chewy tapioca pearls. Medium or large.",
    price: "$4.99",
    img: "Bubble Milk Tea.jpg",
    tag: "Drinks",
  },
];

const MENU = [
  {
    vi: "Phở",
    en: "Beef & Rice Noodle Soup",
    note: "Served all day",
    items: [
      { code: "P-01", name: "The Joy Of Phở — Đặc Biệt", en: "House special combination rice noodle", price: "$15.99" },
      { code: "P-02", name: "Phở Tái", en: "Rare beef rice noodle", price: "$15.99" },
      { code: "P-03", name: "Phở Nạm", en: "Brisket rice noodle", price: "$15.99" },
      { code: "P-04", name: "Phở Tái Nạm", en: "Rare beef with brisket rice noodle", price: "$15.99" },
      { code: "P-05", name: "Phở Tái, Xách", en: "Rare beef with tripe rice noodle", price: "$15.99" },
      { code: "P-06", name: "Phở Tái, Gân", en: "Rare beef with tendon rice noodle", price: "$15.99" },
      { code: "P-07", name: "Phở Tái, Nạm, Gân", en: "Rare beef, brisket with tendon rice noodle", price: "$15.99" },
      { code: "P-08", name: "Phở Tái, Nạm, Xách", en: "Rare beef, brisket with tripe rice noodle", price: "$15.99" },
      { code: "P-09", name: "Phở Tái, Nạm, Gân, Xách", en: "Rare beef, brisket, tendon with tripe rice noodle", price: "$15.99" },
      { code: "P-10", name: "Phở Bò Viên", en: "Beef meatball rice noodle", price: "$15.99" },
      { code: "P-11", name: "Phở Tái Bò Viên", en: "Rare beef with meatball rice noodle", price: "$15.99" },
      { code: "P-12", name: "Phở Gà", en: "Chicken rice noodle soup", price: "$15.99" },
      { code: "P-13", name: "Phở Chay", en: "Vegetable rice noodle soup / tofu", price: "$15.99" },
      { code: "P-14", name: "Phở Tomyum Hải Sản", en: "Tomyum rice noodle with seafood", price: "$16.99" },
      { code: "P-15", name: "Phở Tomyum Bò", en: "Tomyum rice noodle with beef", price: "$15.99" },
      { code: "P-16", name: "Phở Tomyum Gà", en: "Tomyum rice noodle with chicken", price: "$15.99" },
      { code: "P-17", name: "Phở Không", en: "Plain noodle", price: "$7.99" },
    ],
  },
  {
    vi: "Khai Vị",
    en: "Appetizers",
    items: [
      { code: "A-03", name: "Chả Giò Chay", en: "Vegetarian spring rolls (4 rolls)", price: "$8.99" },
      { code: "A-04", name: "Gỏi Cuốn Chay", en: "Vegetarian salad rolls (2 rolls)", price: "$8.99" },
      { code: "A-05", name: "Gỏi Cuốn Tôm Hoặc Thịt", en: "Prawn or pork salad rolls (2 rolls)", price: "$8.99" },
      { code: "A-06", name: "Gỏi Cuốn Tôm Thịt", en: "Prawn and pork salad rolls (2 rolls)", price: "$8.99" },
      { code: "A-07", name: "Gỏi Cuốn Thịt Heo Nướng Sả", en: "Grilled lemongrass pork salad rolls (2 rolls)", price: "$8.99" },
      { code: "A-08", name: "Gỏi Cuốn Gà Nướng Sả", en: "Grilled lemongrass chicken salad rolls (2 rolls)", price: "$8.99" },
      { code: "A-09", name: "Gỏi Cuốn Bò Nướng Sả", en: "Grilled lemongrass beef salad rolls (2 rolls)", price: "$8.99" },
      { code: "A-10", name: "Chạo Tôm", en: "Prawn paste on sugar cane", price: "$9.99" },
      { code: "A-11", name: "Gỏi Xoài Với Tôm", en: "Mango salad with shrimp", price: "$19.99" },
      { code: "A-12", name: "Soup Bò Viên", en: "Beef ball soup", price: "$8.99" },
    ],
  },
  {
    vi: "Bánh Mì",
    en: "Vietnamese Sandwiches",
    items: [
      { code: "Bm-01", name: "Bánh Mì Xíu Mại", en: "Pork meatball Vietnamese sandwich", price: "$8.50" },
      { code: "Bm-02", name: "Bánh Mì Gà Nướng Sả", en: "Grilled lemongrass chicken sandwich", price: "$8.50" },
      { code: "Bm-03", name: "Bánh Mì Thịt Heo Nướng Sả", en: "Grilled lemongrass pork sandwich", price: "$8.50" },
      { code: "Bm-04", name: "Bánh Mì Ba Rọi Heo Nướng", en: "Grilled pork belly sandwich", price: "$8.50" },
      { code: "BM-05", name: "Bánh Mì Bò Nướng Bulgogi Hàn Quốc", en: "Grilled Korean bulgogi beef sandwich", price: "$10.50" },
      { code: "BM-06", name: "Bánh Mì Bò Nướng", en: "Grilled beef steak sandwich", price: "$9.50" },
    ],
  },
  {
    vi: "Hủ Tiếu & Mì",
    en: "Noodle Soup & Egg Noodle",
    items: [
      { code: "H-01", name: "Hủ Tiếu Nam Vang", en: "Phnom Penh noodle soup", price: "$16.99" },
      { code: "H-02", name: "Hủ Tiếu Thập Cẩm", en: "Clear noodle with pork & seafood", price: "$16.99" },
      { code: "H-03", name: "Mì Thập Cẩm", en: "Yellow egg noodle with pork & seafood", price: "$16.99" },
      { code: "H-04", name: "Hủ Tiếu Hải Sản", en: "Clear noodle with seafood", price: "$16.99" },
      { code: "H-05", name: "Mì Vằn Thắn", en: "Yellow egg noodle with wonton", price: "$15.99" },
      { code: "H-06", name: "Vằn Thắn", en: "Wonton soup", price: "$15.99" },
      { code: "H-09", name: "Hủ Tiếu Chay", en: "Vegetarian clear noodle", price: "$15.99" },
      { code: "H-10", name: "Mì Chay", en: "Vegetarian yellow egg noodle", price: "$15.99" },
      { code: "H-11", name: "Miến Gà", en: "Glass noodle with chicken", price: "$15.99" },
      { code: "H-12", name: "Phở Hải Sản", en: "Seafood rice noodle soup", price: "$16.99" },
    ],
  },
  {
    vi: "Hủ Tiếu Xào",
    en: "Sautéed Rice Noodle",
    items: [
      { code: "H-13", name: "Thịt & Hải Sản", en: "Meat & seafood", price: "$17.99" },
      { code: "H-14", name: "Rau Củ", en: "Vegetable", price: "$15.99" },
      { code: "H-15", name: "Bò", en: "Beef", price: "$15.99" },
      { code: "H-16", name: "Gà", en: "Chicken", price: "$15.99" },
      { code: "H-17", name: "Tôm", en: "Shrimp", price: "$17.99" },
      { code: "H-18", name: "Mực", en: "Squid", price: "$17.99" },
    ],
  },
  {
    vi: "Mì Xào Mềm",
    en: "Fried Soft Yellow Egg Noodle",
    items: [
      { code: "MX-1", name: "Thịt & Hải Sản", en: "With meat & seafood", price: "$17.99" },
      { code: "MX-2", name: "Rau Củ", en: "With vegetable", price: "$15.99" },
      { code: "MX-3", name: "Bò", en: "With beef", price: "$15.99" },
      { code: "MX-4", name: "Gà", en: "With chicken", price: "$15.99" },
      { code: "MX-5", name: "Tôm", en: "With shrimp", price: "$17.99" },
      { code: "MX-6", name: "Mực", en: "With squid", price: "$17.99" },
    ],
  },
  {
    vi: "Mì Xào Giòn",
    en: "Fried Crispy Yellow Egg Noodle",
    items: [
      { code: "MX-7", name: "Thịt & Hải Sản", en: "With meat & seafood", price: "$17.99" },
      { code: "MX-8", name: "Rau Củ", en: "With vegetable", price: "$15.99" },
      { code: "MX-9", name: "Bò", en: "With beef", price: "$15.99" },
      { code: "MX-10", name: "Gà", en: "With chicken", price: "$15.99" },
      { code: "MX-11", name: "Tôm", en: "With shrimp", price: "$17.99" },
      { code: "MX-12", name: "Mực", en: "With squid", price: "$17.99" },
    ],
  },
  {
    vi: "Pad Thai",
    en: "Thai-Style Stir-Fried Noodle",
    items: [
      { code: "PT-01", name: "Pad Thái Bò", en: "Pad Thai with beef", price: "$16.99" },
      { code: "PT-02", name: "Pad Thái Gà", en: "Pad Thai with chicken", price: "$16.99" },
      { code: "PT-03", name: "Pad Thái Rau Củ", en: "Pad Thai with vegetable", price: "$16.99" },
      { code: "PT-04", name: "Pad Thái Tôm", en: "Pad Thai with shrimp", price: "$17.99" },
    ],
  },
  {
    vi: "Bánh Canh Bột Lọc",
    en: "Tapioca Noodle Soup",
    items: [
      { code: "BC-01", name: "Heo", en: "Tapioca noodle soup with pork", price: "$15.99" },
      { code: "BC-02", name: "Chả Cá", en: "Tapioca noodle soup with fish cake", price: "$15.99" },
      { code: "BC-03", name: "Tôm", en: "Tapioca noodle soup with shrimp", price: "$15.99" },
    ],
  },
  {
    vi: "Bún",
    en: "Vermicelli Bowls",
    items: [
      { code: "BU-01", name: "Bún Bò Huế", en: "Spicy noodle with beef, pork and ham", price: "$15.99" },
      { code: "BU-02", name: "Bún Riêu Cua", en: "Crab noodle soup with tofu, tomato, pork & ham", price: "$16.99" },
      { code: "BU-03", name: "Bún Thịt Heo Nướng Sả", en: "Grilled lemongrass pork", price: "$15.99" },
      { code: "BU-04", name: "Bún Thịt Heo Nướng Sả & Chả Giò", en: "Grilled lemongrass pork and spring rolls", price: "$16.99" },
      { code: "BU-05", name: "Bún Gà Nướng Sả", en: "Grilled lemongrass chicken", price: "$15.99" },
      { code: "BU-06", name: "Bún Gà Nướng Sả & Chả Giò", en: "Grilled lemongrass chicken and spring rolls", price: "$16.99" },
      { code: "BU-07", name: "Bún Bò Nướng Sả", en: "Grilled lemongrass beef", price: "$15.99" },
      { code: "BU-08", name: "Bún Bò Nướng Sả & Chả Giò", en: "Grilled lemongrass beef and spring rolls", price: "$16.99" },
      { code: "BU-11", name: "Bún Chả Giò", en: "Spring rolls", price: "$15.99" },
      { code: "BU-12", name: "Bún Bò Sườn Nướng Hàn Quốc", en: "Korean-style grilled rib beef vermicelli bowl", price: "$18.99" },
    ],
  },
  {
    vi: "Cơm Tấm",
    en: "Broken Rice Plates",
    items: [
      { code: "CT-01", name: "Cơm Tấm Đặc Biệt", en: "House special — grilled pork chop, Vietnamese sausage & fried egg", price: "$16.99" },
      { code: "CT-02", name: "Cơm Tấm Sườn Nướng Sả", en: "Grilled lemongrass pork chop, sausage & fried egg", price: "$15.99" },
      { code: "CT-03", name: "Cơm Tấm Gà Nướng Sả", en: "Grilled lemongrass chicken, sausage & fried egg", price: "$15.99" },
      { code: "CT-04", name: "Cơm Tấm Bò Nướng Sả", en: "Grilled lemongrass beef, sausage & fried egg", price: "$15.99" },
      { code: "CT-05", name: "Cơm Tấm Thịt Heo Nướng Sả", en: "Grilled lemongrass pork, sausage & fried egg", price: "$15.99" },
    ],
  },
  {
    vi: "Cơm",
    en: "Rice Plates",
    items: [
      { code: "C-01", name: "Cơm Đặc Biệt", en: "House special — grilled pork chop, sausage & fried egg", price: "$16.99" },
      { code: "C-02", name: "Cơm Sườn Nướng Sả", en: "Grilled lemongrass pork chop, sausage & fried egg", price: "$15.99" },
      { code: "C-03", name: "Cơm Gà Nướng Sả", en: "Grilled lemongrass chicken, sausage & fried egg", price: "$15.99" },
      { code: "C-04", name: "Cơm Bò Nướng Sả", en: "Grilled lemongrass beef, sausage & fried egg", price: "$15.99" },
      { code: "C-05", name: "Cơm Thịt Heo Nướng Sả", en: "Grilled lemongrass pork, sausage & fried egg", price: "$15.99" },
      { code: "C-06", name: "Cơm Chiên Giòn Kiểu Nhật", en: "Steamed rice with crispy pork, Japanese style", price: "$18.99" },
      { code: "C-07", name: "Cơm Sườn Bò Nướng Kiểu Hàn Quốc", en: "Korean-style steamed rice with grilled rib beef", price: "$18.99" },
    ],
  },
  {
    vi: "Cơm Chiên",
    en: "Fried Rice",
    items: [
      { code: "CC-01", name: "Cơm Chiên Dương Châu", en: "Yangzhou fried rice", price: "$15.99" },
      { code: "CC-02", name: "Cơm Chiên Hải Sản", en: "Seafood fried rice", price: "$17.99" },
      { code: "CC-03", name: "Cơm Chiên Xá Xíu", en: "BBQ pork fried rice", price: "$15.99" },
      { code: "CC-04", name: "Cơm Chiên Gà", en: "Chicken fried rice", price: "$15.99" },
      { code: "CC-05", name: "Cơm Chiên Tôm", en: "Shrimp fried rice", price: "$16.99" },
      { code: "CC-06", name: "Cơm Chiên Cá Mặn", en: "Salted fish fried rice", price: "$16.99" },
      { code: "CC-07", name: "Cơm Chiên Thái Bò", en: "Beef Thai fried rice", price: "$15.99" },
      { code: "CC-08", name: "Cơm Chiên Thái Gà", en: "Chicken Thai fried rice", price: "$15.99" },
      { code: "CC-09", name: "Cơm Chiên Thái Tôm", en: "Shrimp Thai fried rice", price: "$16.99" },
      { code: "CC-10", name: "Cơm Chiên Rau Củ", en: "Vegetable fried rice", price: "$15.99" },
      { code: "CC-11", name: "Cơm Chiên Hải Sản Kiểu Thái", en: "Seafood fried rice, Thai style", price: "$17.99" },
    ],
  },
  {
    vi: "Cháo",
    en: "Congee",
    items: [
      { code: "CH-02", name: "Cháo Hải Sản", en: "Seafood congee", price: "$14.99" },
      { code: "CH-03", name: "Giò Cháo Quẩy", en: "Chinese breadstick (1 piece)", price: "$2.99" },
    ],
  },
  {
    vi: "Cơm Gia Đình",
    en: "Family Meal",
    items: [
      { code: "FM-01", name: "Cánh Gà Chiên Nước Mắm", en: "Fish sauce chicken wings", price: "$17.99" },
      { code: "FM-02", name: "Cánh Gà Rang Muối", en: "Salted chicken wings", price: "$17.99" },
      { code: "FM-03", name: "Tàu Hủ Rang Muối", en: "Salted tofu", price: "$17.99" },
      { code: "FM-04", name: "Bò Xào Sả Ớt", en: "Beef sautéed with lemongrass & hot pepper", price: "$17.99" },
      { code: "FM-05", name: "Gà Xào Sả Ớt", en: "Chicken sautéed with lemongrass & hot pepper", price: "$17.99" },
      { code: "FM-06", name: "Mực Xào Sả Ớt", en: "Squid sautéed with lemongrass & hot pepper", price: "$17.99" },
      { code: "FM-08", name: "Mực Xào Chua Ngọt", en: "Sweet & sour squid", price: "$18.99" },
      { code: "FM-09", name: "Mực Rang Muối", en: "Deep fried squid with salt & pepper", price: "$18.99" },
      { code: "FM-10", name: "Mực Xào Sa Tế", en: "Stir-fried squid with satay", price: "$18.99" },
      { code: "FM-12", name: "Cá Kho Tộ", en: "Marinated fish in clay pot", price: "$17.99" },
      { code: "FM-13", name: "Canh Chua (Cá / Tôm / Mực)", en: "Sweet & sour soup (fish / shrimp / squid)", price: "$19.99" },
      { code: "FM-14", name: "Canh Rau Cải Thịt Bằm", en: "Vegetable soup with minced meat", price: "$17.99" },
      { code: "FM-15", name: "Rau Cải Xào (Bò / Gà / Đậu Hủ)", en: "Sautéed vegetable (beef / chicken / tofu)", price: "$17.99" },
      { code: "FM-16", name: "Rau Cải Xào (Tôm / Hải Sản)", en: "Sautéed vegetable (shrimp / seafood)", price: "$18.99" },
    ],
  },
  {
    vi: "Cơm Phần",
    en: "Combo Rice Sets",
    items: [
      { code: "CB-02", name: "Combo For 2", en: "Marinated fish in clay pot, stir-fried seasonal vegetable with garlic, steamed rice (2) & sweet & sour soup", price: "$45.99" },
      { code: "CB-04", name: "Combo For 4", en: "Clay pot fish, garlic vegetable, lemongrass chili chicken, steamed rice (4) & sweet & sour soup", price: "$65.99" },
    ],
  },
  {
    vi: "Lẩu",
    en: "Hotpot",
    items: [
      { code: "HP-01", name: "Lẩu Thái (Bò + Hải Sản)", en: "Thai hotpot (beef + seafood)", price: "$45.99" },
      { code: "HP-02", name: "Lẩu Bò Nhúng Giấm", en: "Beef hotpot dipped in vinegar", price: "$45.99" },
    ],
  },
  {
    vi: "Joy of Bubble",
    en: "Bubble Milk Tea",
    note: "Medium or large",
    items: [
      { code: "M-01", name: "Brown Sugar Bubble Tea", en: "Rich brown sugar milk tea with tapioca pearls", price: "$4.99" },
      { code: "M-02", name: "Black Milk Tea", en: "Rich black milk tea, optional tapioca pearls", price: "$4.99" },
      { code: "M-04", name: "Taro Milk Tea", en: "Taro milk tea with tapioca pearls", price: "$4.99" },
      { code: "M-05", name: "Chocolate Milk Tea", en: "Chocolate milk tea, optional tapioca pearls", price: "$4.99" },
      { code: "M-06", name: "Mango Milk Tea", en: "Mango milk tea, served as bubble tea", price: "$4.99" },
      { code: "M-07", name: "Strawberry Milk Tea", en: "Strawberry milk tea with tapioca pearls", price: "$4.99" },
      { code: "M-08", name: "Honeydew Milk Tea", en: "Honeydew milk tea, optional tapioca pearls", price: "$4.99" },
    ],
  },
  {
    vi: "Nước Uống & Tráng Miệng",
    en: "Drinks & Dessert",
    items: [
      { code: "D-01", name: "Cà Phê Đen Đá", en: "Iced coffee (without condensed milk)", price: "$5.99" },
      { code: "D-02", name: "Cà Phê Sữa Đá", en: "Vietnamese iced coffee (with condensed milk)", price: "$5.99" },
    ],
  },
];
